[package]
name = "localserver"
version = "0.1.0"
edition = "2024"

[dependencies]
mio = { version = "1.1.0", features = ["net", "os-poll"] }
uuid = { version = "1.19", features = ["v4"] }
urlencoding = "2.1.3"
httpdate = "1.0.3"