servers:
  - server_name: "example.com"
    host: 127.0.0.1
    ports:
      - 8080
      - 8081
    default_server: true
    root: "./public"
    client_max_body_size: 5000000
    error_pages:
      404: "./error_pages/404.html"
      500: "./error_pages/500.html"
    routes:
      - path: "/login"
        methods: ["GET"]
        root: "/var/www/html"
        default_file: "login.html"

      - path: "/"
        methods: ["GET", "POST"]
        root: "/var/www/html"
        default_file: "index.html"
      
      - path: "/blog"
        methods: ["GET" , "DELETE", "POST"]
        root: "/var/www/blog/"
        default_file: "home.html"
        list_directory: true
      
      - path: "/api"
        methods: ["GET", "POST"]
        root: "/var/www/api"
        redirect: "https://api.example.com"
      
      - path: "/cgi-bin"
        methods: ["GET", "POST"]
        root: "/var/www/cgi"
        list_directory: true
        cgi: ".py"

  - server_name: "blog.example.com"
    host: 127.0.0.1
    ports:
      - 8082
    default_server: false
    routes:
      - path: "/"
        methods: ["GET"]
        root: "/var/www/html"
        default_file: "index.html"